# Generated by Django 3.2 on 2024-05-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geoname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geonameid', models.IntegerField()),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Hазвание')),
                ('asciiname', models.CharField(db_index=True, max_length=200, verbose_name='Hазвание(ascii)')),
                ('alternatenames', models.CharField(db_index=True, max_length=10000, verbose_name='Альтернативные названия')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('feature_class', models.CharField(db_index=True, max_length=1, verbose_name='feature_class')),
                ('feature_code', models.CharField(db_index=True, max_length=10, verbose_name='feature_code')),
                ('country_code', models.CharField(db_index=True, max_length=2, verbose_name='country_code')),
                ('cc2', models.CharField(db_index=True, max_length=200, verbose_name='cc2')),
                ('admin1_code', models.CharField(db_index=True, max_length=20, verbose_name='admin1_code')),
                ('admin2_code', models.CharField(db_index=True, max_length=80, verbose_name='admin1_code')),
                ('admin3_code', models.CharField(db_index=True, max_length=20, verbose_name='admin1_code')),
                ('admin4_code', models.CharField(db_index=True, max_length=20, verbose_name='admin1_code')),
                ('population', models.BigIntegerField()),
                ('elevation', models.IntegerField()),
                ('dem', models.IntegerField()),
                ('timezone', models.IntegerField()),
                ('modification_date', models.DateField()),
            ],
        ),
    ]
