# Generated by Django 3.2 on 2024-05-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoname',
            name='dem',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geoname',
            name='elevation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geoname',
            name='latitude',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='geoname',
            name='longitude',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='geoname',
            name='modification_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geoname',
            name='population',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geoname',
            name='timezone',
            field=models.CharField(max_length=100),
        ),
    ]
