# Generated by Django 3.2 on 2024-05-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20240513_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoname',
            name='geonameid',
            field=models.CharField(max_length=10),
        ),
    ]
