# Generated by Django 3.2 on 2024-05-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_auto_20240513_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoname',
            name='dem',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
